// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIsRdlNG18v-RSRN1Ti90H4xns8hT3QGU',
    appId: '1:305824296312:web:f2f54b71bc12d0f57c2c8d',
    messagingSenderId: '305824296312',
    projectId: 'hercare-dhs',
    authDomain: 'hercare-dhs.firebaseapp.com',
    storageBucket: 'hercare-dhs.firebasestorage.app',
    measurementId: 'G-69TNTCMMDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcKYp1ADPHffcGfQ607NPZvqJ1XuzWUJI',
    appId: '1:305824296312:android:fdbe23c55e95e3967c2c8d',
    messagingSenderId: '305824296312',
    projectId: 'hercare-dhs',
    storageBucket: 'hercare-dhs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtz6TdFvC32CZS9fFhaG--gLSjRY6kA2A',
    appId: '1:305824296312:ios:f654d5f82e1936a47c2c8d',
    messagingSenderId: '305824296312',
    projectId: 'hercare-dhs',
    storageBucket: 'hercare-dhs.firebasestorage.app',
    iosBundleId: 'com.example.myDesktopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtz6TdFvC32CZS9fFhaG--gLSjRY6kA2A',
    appId: '1:305824296312:ios:f654d5f82e1936a47c2c8d',
    messagingSenderId: '305824296312',
    projectId: 'hercare-dhs',
    storageBucket: 'hercare-dhs.firebasestorage.app',
    iosBundleId: 'com.example.myDesktopApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIsRdlNG18v-RSRN1Ti90H4xns8hT3QGU',
    appId: '1:305824296312:web:c95c1bafe726f50f7c2c8d',
    messagingSenderId: '305824296312',
    projectId: 'hercare-dhs',
    authDomain: 'hercare-dhs.firebaseapp.com',
    storageBucket: 'hercare-dhs.firebasestorage.app',
    measurementId: 'G-P0F2WSVK2Q',
  );
}
