// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfEztq4TPWf8H_PrwgrQgH_O-1tIhIXcY',
    appId: '1:67387531775:web:d06572c25ccf608f6c47ca',
    messagingSenderId: '67387531775',
    projectId: 'test1-19246',
    authDomain: 'test1-19246.firebaseapp.com',
    storageBucket: 'test1-19246.firebasestorage.app',
    measurementId: 'G-DEGTZH9SQH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyZePKCVtm8suV37VTL4VveeXz4FFDlpQ',
    appId: '1:67387531775:android:c8a32bd23f3f5a6a6c47ca',
    messagingSenderId: '67387531775',
    projectId: 'test1-19246',
    storageBucket: 'test1-19246.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8nVrvg26JvJncoWlmqnNh1nDHYIpTel0',
    appId: '1:67387531775:ios:e2e548e00fe3c5536c47ca',
    messagingSenderId: '67387531775',
    projectId: 'test1-19246',
    storageBucket: 'test1-19246.firebasestorage.app',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8nVrvg26JvJncoWlmqnNh1nDHYIpTel0',
    appId: '1:67387531775:ios:e2e548e00fe3c5536c47ca',
    messagingSenderId: '67387531775',
    projectId: 'test1-19246',
    storageBucket: 'test1-19246.firebasestorage.app',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfEztq4TPWf8H_PrwgrQgH_O-1tIhIXcY',
    appId: '1:67387531775:web:c3ab990e4efe22b06c47ca',
    messagingSenderId: '67387531775',
    projectId: 'test1-19246',
    authDomain: 'test1-19246.firebaseapp.com',
    storageBucket: 'test1-19246.firebasestorage.app',
    measurementId: 'G-QKD9T3HD0X',
  );
}
